remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#theme: minima
title: Learning Rust
author: egls
description: Some notes taken on the path to learn the rust language
